- name: Copy docker-compose
  copy:
    src: docker-compose.yaml
    dest: .
    
- name: Run docker compose
  community.docker.docker_compose_v2:
    project_src: .
  register: output

- name: Print output
  debug:
    var: output

- name: Check webapp
  ansible.builtin.uri:
    url: http://localhost:5000
  register: _result
  until: _result.status == 200
  retries: 10
  delay: 5